[features]
seeds = false
skip-lint = false
# [programs.localnet]
[programs.devnet]
solana_anchor_metaplex_mint_nfts = "CgiJkL1bjbHggS4mwQMx4cJR7JYQxcRjADvAjhpmzKFe"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "localnet"
cluster = "devnet"
wallet = "/Users/gaylonalfano/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# NOTE Attempt to fix Error processing Instruction 0: instruction expected an executable account
# Read for details: https://discord.com/channels/889577356681945098/889702325231427584/959491746440572938
# Read Anchor.toml docs: https://book.anchor-lang.com/anchor_references/anchor-toml_reference.html#testvalidator

[test.validator]
url = "devnet" # This is the url of the cluster that accounts are cloned from (See `test.validator.clone`)
# url = "https://api.mainnet-beta.solana.com"
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" # The Metaplex token program
[[test.validator.clone]]
address = "PwDiXFxQsGra4sFFTT8r1QWRMd4vfumiWC1jfWNfdYT" # The program's data account (i.e., the account that holds the MP program itself!)

